import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter"
import { ReactNode } from "react"
import { ThemeProviderClient } from "@/styles/ThemeProviderClient"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Funban",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProviderClient>{children}</ThemeProviderClient>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
